package view;

public class ViewLogin extends javax.swing.JFrame {

  public ViewLogin() {
    initComponents();
    this.setResizable(false);
    this.setLocationRelativeTo(null);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    labelTitle = new javax.swing.JLabel();
    labelPassword = new javax.swing.JLabel();
    labelUser = new javax.swing.JLabel();
    txtUser = new javax.swing.JTextField();
    txtPassword = new javax.swing.JPasswordField();
    btnRegister = new javax.swing.JButton();
    btnLogin = new javax.swing.JButton();
    btnExit = new javax.swing.JButton();
    labelValidationUser = new javax.swing.JLabel();
    labelValidationPassword = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setBackground(new java.awt.Color(255, 255, 255));
    jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    labelTitle.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
    labelTitle.setText("INGRESO DE CREDENCIALES");
    jPanel1.add(labelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));

    labelPassword.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
    labelPassword.setText("Contraseña:");
    jPanel1.add(labelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

    labelUser.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
    labelUser.setText("Usuario:");
    jPanel1.add(labelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));
    jPanel1.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 200, -1));
    jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 200, -1));

    btnRegister.setForeground(new java.awt.Color(11, 87, 208));
    btnRegister.setText("Registrarse");
    btnRegister.setBackground(new java.awt.Color(255,255,255));
    btnRegister.setBorderPainted(false);
    btnRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnRegister.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnRegisterActionPerformed(evt);
      }
    });
    jPanel1.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, -1, 20));

    btnLogin.setBackground(new java.awt.Color(204, 255, 204));
    btnLogin.setForeground(new java.awt.Color(0, 102, 51));
    btnLogin.setText("Iniciar sesion");
    btnLogin.setBorderPainted(false);
    btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 120, 30));

    btnExit.setBackground(new java.awt.Color(255, 204, 204));
    btnExit.setForeground(new java.awt.Color(153, 0, 0));
    btnExit.setText("Salir");
    btnExit.setBorderPainted(false);
    btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 100, 30));

    labelValidationUser.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
    labelValidationUser.setForeground(new java.awt.Color(255, 0, 0));
    labelValidationUser.setText(" ");
    jPanel1.add(labelValidationUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 200, -1));

    labelValidationPassword.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
    labelValidationPassword.setForeground(new java.awt.Color(255, 0, 0));
    labelValidationPassword.setText(" ");
    jPanel1.add(labelValidationPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 200, -1));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(12, 12, 12)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(12, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(12, Short.MAX_VALUE)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(12, 12, 12))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_btnRegisterActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new ViewLogin().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  public javax.swing.JButton btnExit;
  public javax.swing.JButton btnLogin;
  public javax.swing.JButton btnRegister;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JLabel labelPassword;
  private javax.swing.JLabel labelTitle;
  private javax.swing.JLabel labelUser;
  public javax.swing.JLabel labelValidationPassword;
  public javax.swing.JLabel labelValidationUser;
  public javax.swing.JPasswordField txtPassword;
  public javax.swing.JTextField txtUser;
  // End of variables declaration//GEN-END:variables
}
