package view;

public class ViewRegister extends javax.swing.JFrame {

  public ViewRegister() {
    initComponents();
    this.setLocationRelativeTo(null);
    this.setResizable(false);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    labelRegister = new javax.swing.JLabel();
    labelLastname = new javax.swing.JLabel();
    labelName = new javax.swing.JLabel();
    txtLastname = new javax.swing.JTextField();
    txtName = new javax.swing.JTextField();
    txtDni = new javax.swing.JTextField();
    labelDni = new javax.swing.JLabel();
    txtDate = new javax.swing.JTextField();
    labelDate = new javax.swing.JLabel();
    labelValidationDate = new javax.swing.JLabel();
    labelValidationName = new javax.swing.JLabel();
    labelValidationLastname = new javax.swing.JLabel();
    labelValidationDni = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    btnClear = new javax.swing.JButton();
    btnRegister = new javax.swing.JButton();
    btnBack = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setBackground(new java.awt.Color(255, 255, 255));
    jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    labelRegister.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
    labelRegister.setText("REGISTRO");
    jPanel1.add(labelRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

    labelLastname.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
    labelLastname.setText("Apellidos:");
    jPanel1.add(labelLastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

    labelName.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
    labelName.setText("Nombres:");
    jPanel1.add(labelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));
    jPanel1.add(txtLastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 170, 20));
    jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 170, -1));
    jPanel1.add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 170, -1));

    labelDni.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
    labelDni.setText("Cédula:");
    jPanel1.add(labelDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));
    jPanel1.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 170, -1));

    labelDate.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
    labelDate.setText("Fecha de nacimiento:");
    jPanel1.add(labelDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));

    labelValidationDate.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
    labelValidationDate.setForeground(new java.awt.Color(255, 0, 0));
    labelValidationDate.setText(" ");
    jPanel1.add(labelValidationDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 170, -1));

    labelValidationName.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
    labelValidationName.setForeground(new java.awt.Color(255, 0, 0));
    labelValidationName.setText(" ");
    jPanel1.add(labelValidationName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 170, -1));

    labelValidationLastname.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
    labelValidationLastname.setForeground(new java.awt.Color(255, 0, 0));
    labelValidationLastname.setText(" ");
    jPanel1.add(labelValidationLastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 170, -1));

    labelValidationDni.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
    labelValidationDni.setForeground(new java.awt.Color(255, 0, 0));
    labelValidationDni.setText(" ");
    jPanel1.add(labelValidationDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 170, -1));

    jPanel2.setBackground(new java.awt.Color(255, 255, 255));

    btnClear.setBackground(new java.awt.Color(245, 245, 245));
    btnClear.setForeground(new java.awt.Color(51, 51, 51));
    btnClear.setText("Limpiar");
    btnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    btnRegister.setBackground(new java.awt.Color(204, 255, 204));
    btnRegister.setForeground(new java.awt.Color(0, 102, 51));
    btnRegister.setText("Registrarse");
    btnRegister.setBorderPainted(false);
    btnRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    btnBack.setBackground(new java.awt.Color(255, 204, 204));
    btnBack.setForeground(new java.awt.Color(153, 0, 0));
    btnBack.setText("Atrás");
    btnBack.setBorderPainted(false);
    btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addGap(10, 10, 10)
        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(16, 16, 16))
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addGap(10, 10, 10)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(15, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(12, 12, 12)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE))
        .addContainerGap(15, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap(12, Short.MAX_VALUE)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(12, 12, 12)
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(12, 12, 12))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(ViewRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(ViewRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(ViewRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(ViewRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new ViewRegister().setVisible(true);
      }
    });
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  public javax.swing.JButton btnBack;
  public javax.swing.JButton btnClear;
  public javax.swing.JButton btnRegister;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JLabel labelDate;
  private javax.swing.JLabel labelDni;
  private javax.swing.JLabel labelLastname;
  private javax.swing.JLabel labelName;
  private javax.swing.JLabel labelRegister;
  public javax.swing.JLabel labelValidationDate;
  public javax.swing.JLabel labelValidationDni;
  public javax.swing.JLabel labelValidationLastname;
  public javax.swing.JLabel labelValidationName;
  public javax.swing.JTextField txtDate;
  public javax.swing.JTextField txtDni;
  public javax.swing.JTextField txtLastname;
  public javax.swing.JTextField txtName;
  // End of variables declaration//GEN-END:variables
}
