/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author ESPE
 */
public class ViewAdmin extends javax.swing.JFrame {

  /**
   * Creates new form ViewAdmin
   */
  public ViewAdmin() {
    initComponents();
    setResizable(false);
    setLocationRelativeTo(null);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    RbTypeGroup = new javax.swing.ButtonGroup();
    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    JScrollEvents = new javax.swing.JScrollPane();
    TableEvents = new javax.swing.JTable();
    TitleTable2 = new javax.swing.JLabel();
    jSeparator1 = new javax.swing.JSeparator();
    TextName = new javax.swing.JTextField();
    TextDate = new javax.swing.JTextField();
    TextPlace = new javax.swing.JTextField();
    jLabel6 = new javax.swing.JLabel();
    TextBand = new javax.swing.JTextField();
    RbConcert = new javax.swing.JRadioButton();
    RbParty = new javax.swing.JRadioButton();
    LabelName = new javax.swing.JLabel();
    LabelDate = new javax.swing.JLabel();
    LabelBand = new javax.swing.JLabel();
    LabelPlace = new javax.swing.JLabel();
    BtnDelete = new javax.swing.JButton();
    BtnEdit = new javax.swing.JButton();
    LbValidationTable = new javax.swing.JLabel();
    BtnSave = new javax.swing.JButton();
    BtnBack = new javax.swing.JButton();
    TitleTable3 = new javax.swing.JLabel();
    jSeparator2 = new javax.swing.JSeparator();
    LbValidationAdd = new javax.swing.JLabel();
    TextPrice = new javax.swing.JTextField();
    jLabel7 = new javax.swing.JLabel();
    LabelPrice = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setBackground(new java.awt.Color(255, 255, 255));

    jLabel1.setText("Nombre");

    jLabel2.setText("Fecha");

    jLabel3.setText("Lugar");

    jLabel4.setText("Banda");

    TableEvents.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "ID", "Nombre", "Fecha", "Lugar", "Banda", "Tipo", "Precio"
      }
    ) {
      boolean[] canEdit = new boolean [] {
        false, false, false, false, false, false, false
      };

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    JScrollEvents.setViewportView(TableEvents);
    if (TableEvents.getColumnModel().getColumnCount() > 0) {
      TableEvents.getColumnModel().getColumn(0).setResizable(false);
      TableEvents.getColumnModel().getColumn(1).setResizable(false);
      TableEvents.getColumnModel().getColumn(2).setResizable(false);
      TableEvents.getColumnModel().getColumn(3).setResizable(false);
      TableEvents.getColumnModel().getColumn(4).setResizable(false);
      TableEvents.getColumnModel().getColumn(5).setResizable(false);
      TableEvents.getColumnModel().getColumn(6).setResizable(false);
    }

    TitleTable2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
    TitleTable2.setForeground(new java.awt.Color(153, 153, 153));
    TitleTable2.setText("Lista eventos");

    jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
    jSeparator1.setForeground(new java.awt.Color(230, 230, 230));

    TextName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));

    TextDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));

    TextPlace.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));

    jLabel6.setText("Tipo");

    TextBand.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
    TextBand.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        TextBandActionPerformed(evt);
      }
    });

    RbConcert.setBackground(new java.awt.Color(255, 255, 255));
    RbTypeGroup.add(RbConcert);
    RbConcert.setText("Concierto");

    RbParty.setBackground(new java.awt.Color(255, 255, 255));
    RbTypeGroup.add(RbParty);
    RbParty.setText("Fiesta");

    LabelName.setBackground(new java.awt.Color(255, 255, 255));
    LabelName.setForeground(new java.awt.Color(255, 0, 0));
    LabelName.setText(" ");

    LabelDate.setBackground(new java.awt.Color(255, 255, 255));
    LabelDate.setForeground(new java.awt.Color(255, 0, 0));
    LabelDate.setText(" ");

    LabelBand.setBackground(new java.awt.Color(255, 255, 255));
    LabelBand.setForeground(new java.awt.Color(255, 0, 0));
    LabelBand.setText(" ");

    LabelPlace.setBackground(new java.awt.Color(255, 255, 255));
    LabelPlace.setForeground(new java.awt.Color(255, 0, 0));
    LabelPlace.setText(" ");

    BtnDelete.setBackground(new java.awt.Color(255, 229, 229));
    BtnDelete.setForeground(new java.awt.Color(204, 102, 0));
    BtnDelete.setText("Eliminar");
    BtnDelete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
    BtnDelete.setBorderPainted(false);

    BtnEdit.setBackground(new java.awt.Color(255, 255, 221));
    BtnEdit.setForeground(new java.awt.Color(153, 153, 0));
    BtnEdit.setText("Editar");
    BtnEdit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
    BtnEdit.setBorderPainted(false);

    LbValidationTable.setForeground(new java.awt.Color(255, 0, 0));
    LbValidationTable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    LbValidationTable.setText(" ");

    BtnSave.setBackground(new java.awt.Color(235, 235, 255));
    BtnSave.setForeground(new java.awt.Color(0, 0, 153));
    BtnSave.setText("Agregar");
    BtnSave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
    BtnSave.setBorderPainted(false);

    BtnBack.setBackground(new java.awt.Color(245, 245, 245));
    BtnBack.setText("Volver");
    BtnBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));

    TitleTable3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
    TitleTable3.setText("EVENTOS");

    jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
    jSeparator2.setForeground(new java.awt.Color(230, 230, 230));

    LbValidationAdd.setBackground(new java.awt.Color(255, 255, 255));
    LbValidationAdd.setForeground(new java.awt.Color(255, 0, 0));
    LbValidationAdd.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    LbValidationAdd.setText(" ");

    TextPrice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
    TextPrice.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        TextPriceActionPerformed(evt);
      }
    });

    jLabel7.setText("Precio");

    LabelPrice.setBackground(new java.awt.Color(255, 255, 255));
    LabelPrice.setForeground(new java.awt.Color(255, 0, 0));
    LabelPrice.setText(" ");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(BtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(BtnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(BtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(LbValidationTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGap(24, 24, 24))
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(24, 24, 24)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(TitleTable3, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(TitleTable2, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(JScrollEvents, javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addComponent(LabelName, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                  .addComponent(TextName, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addComponent(LabelDate, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                  .addComponent(TextDate, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addComponent(LabelPlace, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                  .addComponent(TextPlace, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addComponent(LabelBand, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                  .addComponent(TextBand, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addComponent(LabelPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(TextPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabel6)
                .addGap(30, 30, 30)
                .addComponent(RbConcert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RbParty)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addComponent(BtnSave, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                  .addComponent(LbValidationAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGap(24, 24, 24))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jSeparator2)
            .addContainerGap())))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(10, 10, 10)
        .addComponent(TitleTable3)
        .addGap(12, 12, 12)
        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(24, 24, 24)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(TextName)
              .addComponent(TextDate)
              .addComponent(TextPlace)
              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(jLabel2)
                .addComponent(jLabel3)
                .addComponent(jLabel4)
                .addComponent(jLabel6)
                .addComponent(RbConcert)
                .addComponent(RbParty)
                .addComponent(BtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(TextBand, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel7)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(LabelName)
              .addComponent(LabelDate)
              .addComponent(LabelBand)
              .addComponent(LabelPlace)
              .addComponent(LbValidationAdd)))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(TextPrice)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(LabelPrice)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(5, 5, 5)
        .addComponent(TitleTable2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(JScrollEvents, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(3, 3, 3)
        .addComponent(LbValidationTable)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(BtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(BtnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(BtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(24, 24, 24))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(12, 12, 12))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(12, 12, 12)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void TextBandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextBandActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_TextBandActionPerformed

  private void TextPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPriceActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_TextPriceActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(ViewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(ViewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(ViewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(ViewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new ViewAdmin().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  public javax.swing.JButton BtnBack;
  public javax.swing.JButton BtnDelete;
  public javax.swing.JButton BtnEdit;
  public javax.swing.JButton BtnSave;
  private javax.swing.JScrollPane JScrollEvents;
  public javax.swing.JLabel LabelBand;
  public javax.swing.JLabel LabelDate;
  public javax.swing.JLabel LabelName;
  public javax.swing.JLabel LabelPlace;
  public javax.swing.JLabel LabelPrice;
  public javax.swing.JLabel LbValidationAdd;
  public javax.swing.JLabel LbValidationTable;
  public javax.swing.JRadioButton RbConcert;
  public javax.swing.JRadioButton RbParty;
  public javax.swing.ButtonGroup RbTypeGroup;
  public javax.swing.JTable TableEvents;
  public javax.swing.JTextField TextBand;
  public javax.swing.JTextField TextDate;
  public javax.swing.JTextField TextName;
  public javax.swing.JTextField TextPlace;
  public javax.swing.JTextField TextPrice;
  private javax.swing.JLabel TitleTable2;
  private javax.swing.JLabel TitleTable3;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JSeparator jSeparator2;
  // End of variables declaration//GEN-END:variables

}
